name: Auto Movie Trending Crawler

on:
  schedule:
    - cron: "0 */6 * * *" 
    - cron: "0 5 * * *"    
  workflow_dispatch:        

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright pytrends google-api-python-client pandas
          playwright install chromium

      - name: Run crawler
        run: |
          echo "🕒 UTC Time: $(date -u)"
          echo "🇻🇳 Vietnam Time: $(TZ='Asia/Ho_Chi_Minh' date)"
          upload_data.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add *.csv *.json || true
          git commit -m "Auto update trending data [$(date)]" || echo "No changes to commit"
          git push
